# See the documentation for more information:
# https://packit.dev/docs/configuration/

upstream_package_name: dasbus
downstream_package_name: python-dasbus
specfile_path: python-dasbus.spec
upstream_tag_template: "v{version}"

srpm_build_deps:
  - make
  - python3
  - python3-build

actions:
  create-archive:
    - 'make archive'
    - 'bash -c "cp dist/*.tar.gz ."'
    - 'bash -c "ls *.tar.gz"'

jobs:
  - job: tests
    trigger: pull_request
    targets:
      - fedora-rawhide

  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-rawhide

  - job: copr_build
    trigger: commit
    targets:
      - fedora-rawhide
    branch: master
    owner: "@rhinstaller"
    project: Anaconda
    preserve_project: True
